BudPost/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BudPost.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class HomeController : Controller
    {

        #region View Actions

        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }

        #endregion View Actions
    }
}

BudPost/Areas/Admin/Controllers/SettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BudPost.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class SettingController : Controller
    {

        #region View Actions

        // GET: Admin/Setting
        public ActionResult Index()
        {
            return View();
        }

        #endregion View Actions
    }
}

BudPost/Controllers/DataUserController.cs
using BudPost.Areas.Admin.Models;
using BudPost.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace BudPost.Controllers
{
    [Authorize(Roles = "admin, user")]
    public class DataUserController : Controller
    {

        private UnitOfWork unitOfWork = new UnitOfWork();

        #region View Actions

        // GET: DataUser
        public ActionResult EditUser()
        {
            long id = WebSecurity.GetUserId(User.Identity.Name);
            DataUser dataUser = unitOfWork.DataUserRepository.MyDataUser();
            
            EditDataUser editDataUser = new EditDataUser();
            editDataUser.DataUser = dataUser;
            editDataUser.Phones = unitOfWork.PhoneRepository.FindPhoneForUser(id);
            
            if (dataUser == null)
            {
                return HttpNotFound();
            }

            return View(editDataUser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUser(EditDataUser editDataUser, IEnumerable<Phone> phones)
        {
            
            if (ModelState.IsValid && editDataUser.DataUser.DataUserId != 0)
            {
                if (editDataUser.phone != null)
                {
                    try
                    {
                        editDataUser.phone.DataUser_DataUserId = WebSecurity.CurrentUserId;
                        unitOfWork.PhoneRepository.CreatePhone(editDataUser.phone);
                    }
                    catch
                    {
                        ModelState.AddModelError("", "ERRO ao criar um novo telefone!");
                    }
                }
                if(phones != null)
                {
                    try
                    {
                        foreach (var phone in phones)
                        {
                            //System.Diagnostics.Debug.WriteLine("PhoneId: " + phone.PhoneId + " - Type: " + phone.Type + " - Number: " + phone.Number + " - DataUser_DataUserId: " + phone.DataUser_DataUserId);
                            unitOfWork.PhoneRepository.UpdatePhone(phone);
                        }                        

                        foreach (var p in phones.Where(p => p.Number == null && p.DataUser_DataUserId == WebSecurity.CurrentUserId))
                        {
                            //System.Diagnostics.Debug.WriteLine("PhoneId: " + p.PhoneId + " - Type: " + p.Type + " - Number: " + p.Number + " - DataUser_DataUserId: " + p.DataUser_DataUserId);
                            unitOfWork.PhoneRepository.Delete(p.PhoneId);
                        }

                        unitOfWork.PhoneRepository.Save();
                    }
                    catch (Exception)
                    {
                        ModelState.AddModelError("", "ERRO ao atualizar os dados do telefone!");
                    }
                }                

                try
                {                    
                    unitOfWork.DataUserRepository.UpdateDataUser(editDataUser.DataUser);
                    editDataUser.Phones = unitOfWork.PhoneRepository.FindPhoneForUser(editDataUser.DataUser.DataUserId);
                    unitOfWork.DataUserRepository.Save();
                    ViewBag.msgAlert = "Dados atualizados com sucesso!";
                    return View(editDataUser);
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", "Não foi possível atualizar os dados desse usuário! ERRO: " + e.ToString());
                    return View(editDataUser);
                }
            }            
            return View(editDataUser);
        }

        public ActionResult AddPhone(long idUser)
        {
            if (idUser != 0)
            {
                try
                {
                    Phone phone = new Phone();
                    phone.DataUser_DataUserId = idUser;
                    unitOfWork.PhoneRepository.CreatePhone(phone);
                    unitOfWork.PhoneRepository.Save();
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Erro!");
                }                                
            }

            DataUser dataUser = unitOfWork.DataUserRepository.MyDataUser();
            EditDataUser editDataUser = new EditDataUser();
            editDataUser.DataUser = dataUser;
            editDataUser.Phones = unitOfWork.PhoneRepository.FindPhoneForUser(idUser);

            return View("EditUser", editDataUser);
        }

        public ActionResult RemovePhone(long id)
        {
            if (id != 0)
            {
                try
                {
                    unitOfWork.PhoneRepository.Delete(id);
                    unitOfWork.PhoneRepository.Save();
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Erro!");
                }
            }

            DataUser dataUser = unitOfWork.DataUserRepository.MyDataUser();
            EditDataUser editDataUser = new EditDataUser();
            editDataUser.DataUser = dataUser;
            long idUser = WebSecurity.GetUserId(User.Identity.Name);
            editDataUser.Phones = unitOfWork.PhoneRepository.FindPhoneForUser(idUser);

            return View("EditUser", editDataUser);
        }

        [HttpPost]
        public ActionResult SavePhone(IEnumerable<Phone> phones)
        {
            try
            {
                foreach (var phone in phones)
                {
                    //System.Diagnostics.Debug.WriteLine("PhoneId: " + phone.PhoneId + " - Type: " + phone.Type + " - Number: " + phone.Number + " - DataUser_DataUserId: " + phone.DataUser_DataUserId);
                    unitOfWork.PhoneRepository.UpdatePhone(phone);
                }

                foreach (var p in phones.Where(p => p.Number == null && p.DataUser_DataUserId == WebSecurity.CurrentUserId))
                {
                    //System.Diagnostics.Debug.WriteLine("PhoneId: " + p.PhoneId + " - Type: " + p.Type + " - Number: " + p.Number + " - DataUser_DataUserId: " + p.DataUser_DataUserId);
                    unitOfWork.PhoneRepository.Delete(p.PhoneId);
                }

                unitOfWork.PhoneRepository.Save();
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "ERRO!");
            }

            long id = WebSecurity.GetUserId(User.Identity.Name);
            DataUser dataUser = unitOfWork.DataUserRepository.MyDataUser();

            EditDataUser editDataUser = new EditDataUser();
            editDataUser.DataUser = dataUser;
            editDataUser.Phones = unitOfWork.PhoneRepository.FindPhoneForUser(id);

            return View("EditUser", editDataUser);
        }

        #endregion View Actions

        #region Json Actions

        [HttpGet]
        public JsonResult GetCountries()
        {
            List<Country> countries = unitOfWork.CountryRepository.Countries.ToList();

            return Json(countries, JsonRequestBehavior.AllowGet);
        }
        
        [HttpGet]
        public JsonResult GetStates(long? countryId)
        {
            List<State> states = unitOfWork.StateRepository.States.Where(s => s.Country_Id.Equals(countryId)).ToList();

            return Json(states, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetCities(long? stateId)
        {
            //System.Diagnostics.Debug.WriteLine("ID : " + stateId);
            List<City> cities = unitOfWork.CityRepository.Cities.Where(s => s.State_Id.Equals(stateId)).ToList();

            return Json(cities, JsonRequestBehavior.AllowGet);
        }        

        #endregion Json Actions
    }
}

BudPost/Controllers/HomeController.cs
using BudPost.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BudPost.Controllers
{
    [Authorize(Roles = "admin, user")]
    public class HomeController : Controller
    {

        private UnitOfWork unitOfWork = new UnitOfWork();

        #region View Actions

        public ActionResult Index()
        {
            return View(unitOfWork.PosterRepository.Posters.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Settings()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpGet]
        public JsonResult GetPoster()
        {
            List<Poster> posters = unitOfWork.PosterRepository.Posters.ToList();

            return Json(posters, JsonRequestBehavior.AllowGet);
        }

        #endregion View Actions
    }
}

BudPost/Controllers/PosterController.cs
using BudPost.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace BudPost.Controllers
{
    [Authorize(Roles = "admin, user")]
    public class PosterController : Controller
    {

        private UnitOfWork unitOfWork = new UnitOfWork();

        #region View Actions

        // GET: Poster
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(Poster poster)
        {
            poster.DataUser_DataUserId = WebSecurity.CurrentUserId;
            //System.Diagnostics.Debug.WriteLine("UserId : " + poster.DataUser_DataUserId + " - Título: " + poster.Title + " - Descrição: " + poster.Description);
            if(ModelState.IsValid)
            {
                try
                {
                    unitOfWork.PosterRepository.CreatePost(poster);
                    unitOfWork.PosterRepository.Save();
                    TempData["MsgAlert"] = "Postado com sucesso!";
                    return RedirectToAction("Create");
                }
                catch (Exception)
                {
                    ModelState.AddModelError("Description", "Erro ao postar!.");
                }                
            }
            TempData["MsgAlert"] = "Falhou!";
            return RedirectToAction("Create");
        }

        #endregion View Actions
    }
}

BudPost/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BudPost/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BudPost/Views/Home/Index.cshtml
@model IEnumerable<BudPost.Models.Poster>

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>{{appName}}</h1>
    <p class="lead">{{appDescription}}</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    
</div>
<!--ui-alert faz referência a directiva uiAlert-->


<div class="row" ng-controller="homeCtrl">
    <div ui-alert title="Ops, aconteceu um problema!" message="error"></div>
    
    <div class="col-md-12">
        <input class="form-control" type="text" ng-model="searchCriteria" placeholder="O que você está buscando?" />
    </div>
    <!--{{message}}-->   
    
    <div class="col-md-4" ng-repeat="poster in posters | filter: searchCriteria">
        <h2>{{poster.Title | nameDefault}}</h2>
        <p>
            {{poster.Description | ellipsis: 100}}
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
       
    
        @* 
            <div class="col-md-4">
                <h2>Getting started</h2>
                <p>
                    ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                    enables a clean separation of concerns and gives you full control over markup
                    for enjoyable, agile development.
                </p>
                <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Get more libraries</h2>
                <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
                <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Web Hosting</h2>
                <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
                <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
            </div>
        *@
</div>

BudPost/Views/Home/Settings.cshtml
@{
    ViewBag.Title = "Settings";
}

<h2>Settings</h2>

<ul>
    <li>@Html.ActionLink("Adicionar postagem", "Create", "Poster")</li>
    <li>@Html.ActionLink("Editar seus dados", "EditUser", "DataUser")</li>
    <li>@Html.ActionLink("Alterar password", "ChangePassword", "Account")</li>
    <li>@Html.ActionLink("Excluir conta", "Exclude", "Account")</li>
</ul>      